version: 2.1

orbs:
  ruby: circleci/ruby@2.0.0
  node: circleci/node@5.0.3
jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.1-node
    steps:
      - checkout
      - ruby/install-deps
      - node/install:
          install-yarn: true
          node-version: '17.0.0'
      - node/install-packages:
          pkg-manager: yarn
  check:
    docker:
      - image: cimg/ruby:3.1.1-node
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check:
          format: progress
          label: Inspecting with Rubocop
      - run:
          name: Slim Lint
          command: bundle exec slim-lint app/views
      - node/install:
          install-yarn: true
          node-version: '17.0.0'
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Lint
          command: yarn lint
  test:
    docker:
      - image: cimg/postgres:14.2
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ci_test
      - image: cimg/postgres:14.2
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: postgres
      PGPASSWORD: "postgres"
      RAILS_ENV: test
      DATABASE_URL: "postgres://postgres:postgres@localhost/ci_test"
      TZ: Asia/Tokyo
    steps:
      - checkout
      - ruby/install-deps
      - node/install:
          install-yarn: true
          node-version: '17.0.0'
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Wait for DB
          command: 'dockerize -wait tcp://localhost:5432 -timeout 1m'
      - run:
          name: Database setup
          command: 'bundle exec rails db:setup'
      - run:
          name: RSpec
          command: 'bundle exec rspec'
workflows:
  build_and_test:
    jobs:
      - build
      - check
      - test
